db:
  image: postgres
  restart: always
  ports:
    - 5432:5432
  volumes:
    - ./data:/var/lib/postgresql/data
redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    restart: always